name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3


  

    # Step 4: Run Tests
    - name: Run Tests
      run: npm test

    # Step 5: Build Project (if applicable)
    - name: Build Project
      run: npm run build

    # Step 6: Deploy to Heroku (adjust for your deployment method)
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku auth:token
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
