name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

  frontend:
    name: Build and Test Frontend (React Native)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

  backend:
    name: Build and Test Backend (Python)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          pytest

  machine-learning:
    name: Build and Test Machine Learning Module (TensorFlow)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ML dependencies
        run: |
          cd ml_model
          pip install -r requirements.txt

      - name: Run ML model tests
        run: |
          cd ml_model
          pytest

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [frontend, backend, machine-learning]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t yourusername/yourapp-frontend:latest ./frontend
          docker build -t yourusername/yourapp-backend:latest ./backend
          docker build -t yourusername/yourapp-ml:latest ./ml_model

      - name: Push Docker image
        run: |
          docker push yourusername/yourapp-frontend:latest
          docker push yourusername/yourapp-backend:latest
          docker push yourusername/yourapp-ml:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml up -d
